export default function TermsPage() {
  return (
    <main style={{ maxWidth: 920, margin: "0 auto", padding: "40px 20px" }}>
      <h1>Terms of Service</h1>

      <p>
        These Terms of Service govern your use of ID Radar and its identity risk
        scanning features.
      </p>

      <h2>1. Purpose of the service</h2>
      <p>
        ID Radar provides an automated estimation of identity exposure and identity
        risk based on publicly available search-result patterns and matching
        signals. The service is informational only.
      </p>

      <h2>2. No guarantee</h2>
      <p>
        We do not guarantee that any result is complete, accurate, current, or
        suitable for a particular purpose. A result does not prove that a profile,
        account, or public record belongs to a specific person.
      </p>

      <h2>3. Permitted use</h2>
      <p>
        You may use this service only:
      </p>
      <ul>
        <li>for your own data, or</li>
        <li>with proper authorization from the person concerned.</li>
      </ul>

      <h2>4. Prohibited use</h2>
      <p>You must not use this service to:</p>
      <ul>
        <li>monitor, profile, or investigate third parties without authorization</li>
        <li>harass, intimidate, or target other individuals</li>
        <li>support identity theft, impersonation, fraud, or social engineering</li>
        <li>misuse the service for unlawful or abusive purposes</li>
      </ul>

      <h2>5. No legal, security, or forensic proof</h2>
      <p>
        Results generated by ID Radar are estimates and heuristics. They are not
        legal advice, forensic proof, or a definitive security assessment.
      </p>

      <h2>6. Availability and changes</h2>
      <p>
        We may modify, restrict, suspend, or discontinue parts of the service at
        any time without prior notice.
      </p>

      <h2>7. External services</h2>
      <p>
        The service may rely on third-party infrastructure, hosting providers, and
        external result providers. We are not responsible for the availability,
        accuracy, or policies of such third parties.
      </p>

      <h2>8. Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, we are not liable for damages,
        losses, or decisions made based on use of this service or its results.
      </p>

      <h2>9. User responsibility</h2>
      <p>
        You are responsible for ensuring that your use of this service complies
        with applicable law and does not infringe the rights of others.
      </p>

      <h2>10. Changes to these terms</h2>
      <p>
        We may update these Terms of Service at any time. The latest version
        published on this page applies.
      </p>
    </main>
  );
}