export default function ImprintPage() {
  return (
    <main style={{ maxWidth: 920, margin: "0 auto", padding: "40px 20px" }}>
      <h1>Imprint</h1>

      <p>
        ID Radar is a web-based service focused on identity exposure and identity
        risk analysis.
      </p>

      <h2>Operator</h2>
      <p>
        Operator information is available upon legitimate request.
      </p>

      <h2>Contact</h2>
      <p>
        Email: <a href="mailto:hello@idradar.ch">hello@idradar.ch</a>
      </p>

      <h2>Disclaimer</h2>
      <p>
        The information on this website is provided for general informational
        purposes only. Results generated by the scanner are estimates and do not
        constitute legal advice, security guarantees, or verified findings.
      </p>

      <h2>Copyright</h2>
      <p>
        Unless otherwise stated, the content of this website is protected by
        applicable copyright and related rights.
      </p>
    </main>
  );
}